name: Deploy CDK Project

on:
  push:
    branches:
      - main

jobs:
    deploy:
      runs-on: ubuntu-latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
  
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
  
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 18

        - name: Install CDK dependencies
          run: |
            cd backend
            npm ci

        - name: Install Frontend dependencies
          run: |
            cd frontend
            npm ci
            mkdir dist
  
        - name: Deploy CDK Rest Api Stack
          run: |
            cd backend
            npx cdk deploy CognitoSecuredRestApi --require-approval never -O cdk-output.json
            echo "VITE_API_URL=$(cat cdk-output.json | grep -oP 'https://\S+execute-api\S+amazonaws\.com/prod/')" > ../frontend/.env
  
        - name: Build Frontend
          run: |
            cd frontend
            npm run build

        - name: Deploy CDK Website Hosting & CDN Stack
          run: |
            cd backend
            npx cdk deploy CognitoSecuredWebsiteDeployment --require-approval never
            